### ISSUE TITLE
CircleCI config needs to be updated to reflect `staging` environment.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/roots#12]
A staging environment has been created for the application. You may have to update the CircleCI configuration like so:

```
deployment:
  prod:
    branch: master
    heroku:
      appname: roots-event-manager
  staging:
    branch: staging
    heroku:
      appname: roots-event-manager-staging
```

In addition, you'll need to update the database configuration to reflect the `staging` environment. Currently, the configuration only has values for `test`, `production` and `development`.
